In [1]:
import pandas as pd
import csv

In [2]:
df = pd.read_csv('zomato_restaurants_with_ratings.csv')
df.head()

,rest_name,locality,cost_for_two,rating,cuisines
0,Asia Kitchen By Mainland China,Koramangala 5th Block,"1,500",4.9,"['Asian', 'Chinese', 'Thai', 'Momos']"
1,Belgian Waffle Factory,Brigade Road,400,4.9,['Desserts']
2,Byg Brewski Brewing Company,Sarjapur Road,"1,600",4.9,"['Continental', 'North Indian', 'Italian', 'So..."
3,Taaza Thindi,Jayanagar,100,4.9,['South Indian']
4,Santé Spa Cuisine,Indiranagar,"1,000",4.9,"['Healthy Food', 'Salad', 'Mediterranean']"

In [3]:
df.shape

(10976, 5)

In [4]:
l = ['South Indian', 'Italian', 'Thai']
nested_list = []
for i in range(0, len(l)):
    list_rest = []
    for j in range(0, 10976):
        if l[i] in df.iloc[j]['cuisines']:
            dataframe = {}
            dataframe['rest_name'] = df.iloc[j]['rest_name']
            dataframe['locality'] = df.iloc[j]['locality']
            dataframe['cost_for_two'] = df.iloc[j]['cost_for_two']
            dataframe['rating'] = df.iloc[j]['rating']
            dataframe['cuisines'] = df.iloc[j]['cuisines']
            list_rest.append(dataframe)
    df1 = pd.DataFrame(list_rest)
    df1 = df1.head(7)
    nested_list.append(df1)
print(nested_list[1])

  cost_for_two                                           cuisines  \
0        1,600  ['Continental', 'North Indian', 'Italian', 'So...
1        1,300  ['Continental', 'North Indian', 'Asian', 'Ital...
2        1,200                  ['Italian', 'Pizza', 'Beverages']
3        1,000  ['Continental', 'Asian', 'Italian', 'North Ind...
4        1,000  ['Continental', 'Italian', 'North Indian', 'Ch...
5          750  ['Chinese', 'American', 'Continental', 'Italia...
6        1,500                   ['Italian', 'American', 'Pizza']

                locality rating                    rest_name
0          Sarjapur Road    4.9  Byg Brewski Brewing Company
1           Marathahalli    4.8               The Globe Grub
2            Indiranagar    4.8             The Pizza Bakery
3                    HSR    4.8               TBC Sky Lounge
4            Indiranagar    4.7             The Twisted Desi
5  Koramangala 5th Block    4.7           ECHOES Koramangala
6            Indiranagar    4.7                         Toit

In [9]:
list(nested_list[1]['cost_for_two'])

['1,600', '1,300', '1,200', '1,000', '1,000', '750', '1,500']

In [25]:
for cuisine, recommendations in zip(l, nested_list):
    print(cuisine)
    rest_name = list(recommendations['rest_name'])
    rating = list(recommendations['rating'])
    locality = list(recommendations['locality'])
    cost_for_two = list(recommendations['cost_for_two'])
    cuisines = list(recommendations['cuisines'])
    length = len(recommendations)
    for i in range(0, length):
        print(rest_name[i]+"\t"+rating[i]+"\t"+locality[i]+"\t"+cost_for_two[i]+"\t"+cuisines[i])

South Indian
Byg Brewski Brewing Company	4.9	Sarjapur Road	1,600	['Continental', 'North Indian', 'Italian', 'South Indian', 'Finger Food']
Taaza Thindi	4.9	Jayanagar	100	['South Indian']
Brahmin's Coffee Bar	4.8	Basavanagudi	100	['South Indian']
CTR	4.7	Malleshwaram	150	['South Indian']
Arogya Ahaara	4.7	HSR	100	['South Indian']
Namma SLN                                     	4.6	Basavanagudi	100	['South Indian']
Sea Rock	4.6	Seshadripuram	1,000	['Mangalorean', 'Seafood', 'South Indian', 'North Indian', 'Chinese', 'Mughlai']
Italian
Byg Brewski Brewing Company	4.9	Sarjapur Road	1,600	['Continental', 'North Indian', 'Italian', 'South Indian', 'Finger Food']
The Globe Grub	4.8	Marathahalli	1,300	['Continental', 'North Indian', 'Asian', 'Italian']
The Pizza Bakery	4.8	Indiranagar	1,200	['Italian', 'Pizza', 'Beverages']
TBC Sky Lounge	4.8	HSR	1,000	['Continental', 'Asian', 'Italian', 'North Indian']
The Twisted Desi	4.7	Indiranagar	1,000	['Continental', 'Italian', 'North Indian', 'Chinese']
ECHOES Koramangala	4.7	Koramangala 5th Block	750	['Chinese', 'American', 'Continental', 'Italian', 'North Indian']
Toit	4.7	Indiranagar	1,500	['Italian', 'American', 'Pizza']
Thai
Asia Kitchen By Mainland China	4.9	Koramangala 5th Block	1,500	['Asian', 'Chinese', 'Thai', 'Momos']
You Mee	4.7	Whitefield	2,000	['Sushi', 'Japanese', 'Chinese', 'Thai']
Rim Naam - The Oberoi	4.6	The Oberoi, MG Road	3,000	['Thai']
Buff Buffet Buff	4.5	BluPetal Hotel, Koramangala	1,500	['North Indian', 'Chinese', 'Continental', 'Thai', 'Salad']
Shao - Radisson Blu	4.5	Radisson Blu, Marathahalli	3,000	['Thai', 'Japanese', 'Chinese']
Republic Of Noodles - Lemon Tree Premier	4.5	Lemon Tree Premier, Ulsoor	1,800	['Malaysian', 'Singaporean', 'Thai']
OKI	4.5	Kammanahalli	1,200	['Asian', 'European', 'Italian', 'Korean', 'Malaysian', 'Thai', 'Vietnamese', 'Chinese']

In [3]:
df_user_ratings = pd.read_csv('zomato_reviews - FINAL.csv')
df_user_ratings.head()

       cust_name  cust_rating     rest_name
0          Priya          4.0  Brahma Brews
1         Jitesh          4.0  Brahma Brews
2       Swetha S          4.0  Brahma Brews
3  Ashwini Gowda          4.0  Brahma Brews
4         Foodie          5.0  Brahma Brews

In [5]:
username = 'Shikha'
df_user_ratings.shape

(17385, 3)

In [8]:
from pymongo import MongoClient

uri = "mongodb://127.0.0.1:27017"
client = MongoClient(uri)
database = client['RestaurantRecommender']
collection = database['user_ratings']

In [17]:
user_collection = collection.find({'cust_name': username})
user = list(user_collection)
print(len(user))
print(user[0])
print(user[0]['rest_name'])

7
{'rest_name': 'Hard Rock Cafe', 'cust_rating': '3.0', '_id': ObjectId('5c95b9bc4746374104f2756e'), 'cust_name': 'Shikha'}
Hard Rock Cafe

In [20]:
for i in range(0, len(user)):
    print(user[i]['rest_name']+"\t"+user[i]['cust_rating'])

Hard Rock Cafe	3.0
Andhra Ruchulu	3.0
Cubbon Pavilion - ITC Gardenia	4.0
Wat-a-Burger!	3.0
Baisakhi	1.0
Richie Rich	4.0
Uttarkhand	1.0

In [29]:
user_collection = collection.find({'cust_name': 'Varsha'})
user = list(user_collection)
if not user:
    print("HELLO")
else:
    print("YOU GOT IT")

HELLO

# Calculating the 'score'

In [3]:
df = pd.read_csv('zomato_restaurants.csv')
df.head()

,rest_index,rest_name,locality,cost_for_two,rating,votes,cuisines
0,0,Punjab Grill,"Orion Mall, Malleshwaram","2,000",4.9,2058,"['North Indian', 'Mughlai']"
1,1,Byg Brewski Brewing Company,Sarjapur Road,"1,600",4.9,17034,"['Continental', 'North Indian', 'Italian', 'So..."
2,2,Brahmin's Coffee Bar,Basavanagudi,100,4.9,2711,['South Indian']
3,3,Taaza Thindi,Jayanagar,100,4.9,4152,['South Indian']
4,4,Santé Spa Cuisine,Indiranagar,"1,000",4.9,279,"['Healthy Food', 'Salad', 'Mediterranean']"

In [188]:
average_rating = df['rating'].mean()
print(average_rating)

3.6083260734287648

In [189]:
# Minimum number of votes required to be in the charts
min_votes = df['votes'].quantile(0.50)
print(min_votes)

38.0

In [190]:
# Restaurants that qualify for the chart
q_rest = df.copy().loc[df['votes'] >= min_votes]
q_rest.shape

(4042, 7)

In [191]:
# Computing weighted rating of each restaurant
def weighted_rating(df, m=min_votes, C=average_rating):
    v = df['votes']
    R = df['rating']
    return (v/(v+m) * R) + (m/(m+v) * C)

In [192]:
q_rest['score'] = round(q_rest.apply(weighted_rating, axis=1), 3)

In [193]:
q_rest = q_rest.sort_values('score', ascending=False)
df_copy = q_rest[['rest_index', 'rest_name', 'locality', 'cost_for_two', 'rating', 'votes', 'score', 'cuisines']]

In [194]:
df_copy.to_csv('zomato_qualified_restaurants.csv', index=False)

# Content-Based Recommendations

In [2]:
df = pd.read_csv('zomato_restaurants.csv')
df.head(10)

,rest_index,rest_name,locality,cost_for_two,rating,votes,cuisines
0,0,Punjab Grill,"Orion Mall, Malleshwaram","2,000",4.9,2058,"['North Indian', 'Mughlai']"
1,1,Byg Brewski Brewing Company,Sarjapur Road,"1,600",4.9,17034,"['Continental', 'North Indian', 'Italian', 'So..."
2,2,Brahmin's Coffee Bar,Basavanagudi,100,4.9,2711,['South Indian']
3,3,Taaza Thindi,Jayanagar,100,4.9,4152,['South Indian']
4,4,Santé Spa Cuisine,Indiranagar,"1,000",4.9,279,"['Healthy Food', 'Salad', 'Mediterranean']"
5,5,Belgian Waffle Factory,Brigade Road,400,4.9,1750,['Desserts']
6,6,Milano Ice Cream,Indiranagar,400,4.8,2168,"['Ice Cream', 'Desserts']"
7,7,The Boozy Griffin,Marathahalli,"1,800",4.8,4843,"['European', 'Continental']"
8,8,O.G. Variar & Sons,Rajajinagar,200,4.8,1169,"['Bakery', 'Desserts']"
9,9,Asia Kitchen By Mainland China,Koramangala 5th Block,"1,500",4.8,2435,"['Asian', 'Chinese', 'Thai', 'Momos']"

In [87]:
print(df.loc[df['rest_name']=='Punjab Grill']['rating'])

0     4.9
13    4.8
Name: rating, dtype: float64

In [5]:
df['cuisines'] = df['cuisines'].fillna("").astype('str')

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
tf = TfidfVectorizer(analyzer='word',ngram_range=(1, 2),min_df=0, stop_words='english')
tfidf_matrix = tf.fit_transform(df['cuisines'])
tfidf_matrix.shape

(8035, 1165)

In [7]:
from sklearn.metrics.pairwise import linear_kernel
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)
cosine_sim[:4, :4]

array([[1.        , 0.08749401, 0.08583853, 0.08583853],
       [0.08749401, 1.        , 0.26098925, 0.26098925],
       [0.08583853, 0.26098925, 1.        , 1.        ],
       [0.08583853, 0.26098925, 1.        , 1.        ]])

In [74]:
# Build a 1-dimensional array with movie titles
titles = df['rest_name']
indices = pd.Series(df.index, index=df['rest_name'])

# Function that get movie recommendations based on the cosine similarity score of movie genres
def genre_recommendations(title):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    rest_indices = [i[0] for i in sim_scores]
    final = titles.iloc[rest_indices].head()
    return final.values

In [75]:
print(genre_recommendations("Taaza Thindi"))

["Brahmin's Coffee Bar" 'Taaza Thindi' 'CTR' 'Oota Bangalore' 'Namma SLN']

### Getting a list of restaurants for which recommendations is not possible

In [25]:
count = 0
non_rec = []
for i in range(0, 8035):
    try:
        genre_recommendations(df['rest_name'][i]).head()
    except:
        dataframe = {}
        dataframe['rest_name'] = df['rest_name'][i]
        non_rec.append(dataframe)
        count += 1
print(count)
print(non_rec[5])

786
{'rest_name': 'Le Arabia'}

In [28]:
df_non_rec = pd.DataFrame(non_rec)
df_non_rec.to_csv('content_based_non_rec.csv', index=False)

### Recommending to a particular user

In [12]:
username = "Priya"

In [102]:
fin = []
if username in user_ratings['cust_name'].values:
    user_collection = collection.find({'cust_name': username})
    user = list(user_collection)
    l = len(user)
    for i in range(0, l):
        list_of_recommendation = []
        if user[i]['rest_name'] in non_rec['rest_name'].values:
            print("NOT: "+user[i]['rest_name'])
        else:
            list_of_recommendation = genre_recommendations(user[i]['rest_name'])
            for i in range(0, len(list_of_recommendation)):
                dataframe = {}
                dataframe['rest_name'] = list_of_recommendation[i]
                dataframe['rating'] = float(df.loc[df['rest_name']== dataframe['rest_name']]['rating'].values[0])
                fin.append(dataframe)
else:
    print("FALSE")

if len(fin)==0:
    print("SORRY! NO Recommendations")
else:
    print(fin)

[{'rating': 4.4, 'rest_name': 'Brahma Brews'}, {'rating': 4.3, 'rest_name': "Bob's Bar"}, {'rating': 3.4, 'rest_name': 'Madhushala'}, {'rating': 4.3, 'rest_name': 'THE RIG'}, {'rating': 4.3, 'rest_name': "Murphy's Brewhouse - The Paul Bangalore"}, {'rating': 4.1, 'rest_name': 'Gufha - The President Hotel'}, {'rating': 4.1, 'rest_name': 'Pashto'}, {'rating': 4.9, 'rest_name': 'Punjab Grill'}, {'rating': 4.4, 'rest_name': 'Le Arabia'}, {'rating': 4.4, 'rest_name': 'Delhi Highway'}, {'rating': 4.0, 'rest_name': 'Potful'}, {'rating': 3.9, 'rest_name': 'Firewood Biryani'}, {'rating': 3.3, 'rest_name': 'Smoke-A-Pot'}, {'rating': 3.8, 'rest_name': 'Salaam Sigri Rolls & Kebabs'}, {'rating': 4.4, 'rest_name': 'Siddiqu Kabab Center'}, {'rating': 4.1, 'rest_name': 'Byblos'}, {'rating': 3.9, 'rest_name': 'Alibaba Cafe and Restaurant'}, {'rating': 3.3, 'rest_name': 'Dabba Gosht'}, {'rating': 4.1, 'rest_name': 'Agape'}, {'rating': 4.3, 'rest_name': 'Habibi Falafel'}, {'rating': 4.0, 'rest_name': 'Roy Hotel & Restaurant'}, {'rating': 4.0, 'rest_name': 'Bengali Fun Foods'}, {'rating': 3.9, 'rest_name': 'Hiyar Majhe Kolkata'}, {'rating': 3.9, 'rest_name': 'Little Kolkata'}, {'rating': 3.8, 'rest_name': 'Sonar Bangala'}, {'rating': 4.0, 'rest_name': 'Cheesiano Pizza'}, {'rating': 3.8, 'rest_name': 'Eagles Pizza'}, {'rating': 3.8, 'rest_name': 'Eagles Pizza'}, {'rating': 3.6, 'rest_name': 'Intalia'}, {'rating': 3.5, 'rest_name': 'Papa Pizza N Kafe'}, {'rating': 3.9, 'rest_name': 'Grand Desi Paratha'}, {'rating': 3.8, 'rest_name': 'Amchoor'}, {'rating': 3.8, 'rest_name': 'Masala Central'}, {'rating': 3.7, 'rest_name': 'Bhukkhad Baba'}, {'rating': 3.3, 'rest_name': 'Delhi Food Point'}, {'rating': 4.0, 'rest_name': 'Cheesiano Pizza'}, {'rating': 3.8, 'rest_name': 'Eagles Pizza'}, {'rating': 3.8, 'rest_name': 'Eagles Pizza'}, {'rating': 3.6, 'rest_name': 'Intalia'}, {'rating': 3.5, 'rest_name': 'Papa Pizza N Kafe'}, {'rating': 4.4, 'rest_name': 'Melange - Radisson Blu'}, {'rating': 3.9, 'rest_name': 'Golden Oak - La Marvella Sarovar Premiere Hotel'}, {'rating': 3.5, 'rest_name': 'Flavours Radha Hometel'}, {'rating': 4.3, 'rest_name': 'Season - Adarsh Hamilton'}, {'rating': 3.5, 'rest_name': 'Rajesh Restaurant'}]

# Collaborative Filtering

In [2]:
df = pd.read_csv('zomato_reviews - FINAL.csv')
df.head()

       cust_name  cust_rating     rest_name
0          Priya          4.0  Brahma Brews
1         Jitesh          4.0  Brahma Brews
2       Swetha S          4.0  Brahma Brews
3  Ashwini Gowda          4.0  Brahma Brews
4         Foodie          5.0  Brahma Brews

In [45]:
userRatings = df.pivot_table(index=['cust_name'], columns=['rest_name'],values='cust_rating')
userRatings.head(252)

rest_name,#BEiR,#L-81 Cafe,#refuel,1000 B.C,1131 Bar + Kitchen,12th Main - Grand Mercure,1441 Pizzeria,1522 - The Pub,154 Breakfast Club,1722 Urban Bistro,...,Zucca Pizzeria,Zucca Pizzeria & Shakes,Zyara,alt,b Café - Shangri-La Hotel,de Ranthal,eat.fit,epulo - Vineyard Restaurant,i-Bar - The Park Bangalore,nu.tree
cust_name,,,,,,,,,,,,,,,,,,,,,
"""Veg""ging It Out!(Chetna)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
$ign,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
$wetz,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
'Vishnu Menon,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
(Aayushi Gupta)(_gourmandize_),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22foodlove,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
@aft_artfoodtravel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Hungry Gobbler,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Wenkat,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AAKASH S PUNJABI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AB,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABC Consultants,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABHIJITH SUDHAKAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABHISHEK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ABHISHEK KUMAR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ADJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AGAMONI GHOSH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AJ,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AJITH G A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
AMAN KEDIA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ANOOP SINGH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ASTHA SHUKLA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A_man_has_eaten,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aadarsh Gupta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aadhi Adira,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aadhi Shree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aadityan R,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aakankshi Gupta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aakarsh Arora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Aakash Modale,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Akarshith Aakash,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akash Agarwal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akash Agrawal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akash Deep,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akash Goel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akash Karki,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akash Kumawat,NaN,NaN,NaN,NaN,NaN,NaN,4.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akash Mishra,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akash Pai,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akash Pattanaik,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akash Prasad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akash Roy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akash Tibriwal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akassh K Arrya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akath Dua,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhi & Avi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhil Adekar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhil Khandeparkar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhil Khatri,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhil Kohli (gourmet.theories),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhil Mehta,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhil Nair,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhil Prasad,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhil Vandanapu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhilesh,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhilesh Attal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhilesh Kumar,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhilesh Math,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akhileshwari Reddy,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Akil Appaiah Kademada,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
corrMatrix = userRatings.corr()
corrMatrix.head(10)

rest_name,#BEiR,#L-81 Cafe,#refuel,1000 B.C,1131 Bar + Kitchen,12th Main - Grand Mercure,1441 Pizzeria,1522 - The Pub,154 Breakfast Club,1722 Urban Bistro,...,Zucca Pizzeria,Zucca Pizzeria & Shakes,Zyara,alt,b Café - Shangri-La Hotel,de Ranthal,eat.fit,epulo - Vineyard Restaurant,i-Bar - The Park Bangalore,nu.tree
rest_name,,,,,,,,,,,,,,,,,,,,,
#BEiR,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
#L-81 Cafe,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
#refuel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000 B.C,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1131 Bar + Kitchen,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12th Main - Grand Mercure,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1441 Pizzeria,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1522 - The Pub,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154 Breakfast Club,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1722 Urban Bistro,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
corrMatrix = userRatings.corr(method='pearson')
corrMatrix.head()

rest_name,#BEiR,#L-81 Cafe,#refuel,1000 B.C,1131 Bar + Kitchen,12th Main - Grand Mercure,1441 Pizzeria,1522 - The Pub,154 Breakfast Club,1722 Urban Bistro,...,Zucca Pizzeria,Zucca Pizzeria & Shakes,Zyara,alt,b Café - Shangri-La Hotel,de Ranthal,eat.fit,epulo - Vineyard Restaurant,i-Bar - The Park Bangalore,nu.tree
rest_name,,,,,,,,,,,,,,,,,,,,,
#BEiR,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
#L-81 Cafe,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
#refuel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1000 B.C,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1131 Bar + Kitchen,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [97]:
userRatings.to_csv('userRatings.csv', index=True)
corrMatrix.to_csv('corrMatrix.csv', index=True)

In [99]:
userR = pd.read_csv('userRatings.csv')
corrM = pd.read_csv('corrMatrix.csv')

In [109]:
userR['cust_name'].head()

0         "Veg"ging It Out!(Chetna)
1                              $ign
2                             $wetz
3                     'Vishnu Menon
4    (Aayushi Gupta)(_gourmandize_)
Name: cust_name, dtype: object

In [178]:
user_index = userR.cust_name[userR.cust_name == 'Sunitha Pai'].index[0]

In [179]:
#Can change user for 0 to any user and obtain recommendation for that user. Just change loc[number].
myRatings = userRatings.iloc[user_index].dropna()
myRatings

rest_name
Adithya                                4.0
Asaivam Restaurant                     3.0
Brew Bakes Cafe                        4.0
Café Mor'ish                           4.0
Capri Gastrobar                        4.0
Churchill's                            1.0
Coast                                  3.0
Coffee Mechanics                       5.0
Desserted                              4.0
Falafel's - The Lebanese Haus          4.0
Food Zone                              3.0
Hotel Annapoorna                       4.0
Indian Coffee House & Restaurant       4.0
Indira Darshini                        4.0
Kadalu Sea Food Restaurant             4.0
Kakal Kai Ruchi                        4.0
Mangalore Kitchen                      4.0
MoXa Bistro                            4.0
Mouthful                               4.0
Namdhari's Salad Bar                   4.0
Namma Kudla                            4.0
Nandi Upachar                          5.0
New Tandoor                            5.0
Palmgrove                              4.0
Prakriti Delux                         3.0
S G Rao’s Military Hotel               3.0
Sabari Juice Junction                  4.0
Sea Spice by 7 Star                    5.0
Seafood Dot Grill                      4.0
Sendhoor Coffee                        4.0
Sri Raghavendra Stores                 4.0
Tasty Bites                            4.0
The Coastal Crew by Fujian on 24th     4.0
The Lobby Lounge - The Ritz-Carlton    5.0
Udupi Grand                            4.0
Urban Solace - Café for the Soul       3.0
Name: Sunitha Pai, dtype: float64

In [180]:
simCandidates = pd.Series()
for i in range(1, len(myRatings.index)):
    #print ("adding sims for " + myRatings.index[i] + "...")
    sims = corrM[myRatings.index[i]].dropna()
    sims = sims.map(lambda x: x * myRatings[i])
    simCandidates = simCandidates.append(sims)

In [181]:
simCandidates.sort_values(inplace = True, ascending = False)
print(simCandidates.head(20))

1445    5.0
801     5.0
2144    5.0
2302    5.0
2204    5.0
2737    5.0
2957    4.0
929     4.0
1299    4.0
2129    4.0
641     4.0
3493    4.0
1622    4.0
2326    4.0
615     4.0
237     4.0
2734    4.0
2738    4.0
969     4.0
2747    4.0
dtype: float64

In [182]:
indexes = simCandidates.index.values

In [183]:
simCandidates = simCandidates.groupby(simCandidates.index).sum()

In [184]:
simCandidates.sort_values(inplace = True, ascending = False)
simCandidates.head()

2326    8.0
2957    8.0
2144    5.0
2737    5.0
2204    5.0
dtype: float64

In [185]:
filteredSims = simCandidates.drop(myRatings.index, errors='ignore')
filteredSims.head(25)

2326    8.0
2957    8.0
2144    5.0
2737    5.0
2204    5.0
2302    5.0
801     5.0
1445    5.0
1500    4.0
1391    4.0
2129    4.0
1622    4.0
969     4.0
929     4.0
641     4.0
615     4.0
237     4.0
1299    4.0
79      4.0
3215    4.0
2734    4.0
2738    4.0
2747    4.0
3493    4.0
3118    4.0
dtype: float64

In [186]:
simCandidates = pd.Series()
for i in range(1, len(myRatings.index)):
    #print ("adding sims for " + myRatings.index[i] + "...")
    sims = corrMatrix[myRatings.index[i]].dropna()
    sims = sims.map(lambda x: x * myRatings[i])
    simCandidates = simCandidates.append(sims)

In [187]:
simCandidates.sort_values(inplace = True, ascending = False)
print(simCandidates.head())

Hungree Belly       5.0
Coffee Mechanics    5.0
Nandi Upachar       5.0
Orzuv               5.0
New Tandoor         5.0
dtype: float64

In [188]:
filteredSims = simCandidates.drop(myRatings.index, errors='ignore')
filteredSims.head(25)

Hungree Belly                      5.0
Orzuv                              5.0
HVR Veg                            4.0
Kailash Parbat                     4.0
Azure - Taj Yeshwantpur            4.0
Sea Rock                           4.0
Donne Biriyani House               4.0
Hotel Kadamba Veg                  4.0
The Konkan - Seafood Restaurant   -2.0
Sanchez Taqueria & Cantina        -3.0
Maravanthe                        -3.0
Gods Own Cafe                     -4.0
The Jade Kitchen                  -4.0
Swathi                            -5.0
dtype: float64

In [189]:
len(filteredSims)

14

In [190]:
myRatings.index

Index(['Adithya', 'Asaivam Restaurant', 'Brew Bakes Cafe', 'Café Mor'ish',
       'Capri Gastrobar', 'Churchill's', 'Coast', 'Coffee Mechanics',
       'Desserted', 'Falafel's - The Lebanese Haus', 'Food Zone',
       'Hotel Annapoorna', 'Indian Coffee House & Restaurant',
       'Indira Darshini', 'Kadalu Sea Food Restaurant', 'Kakal Kai Ruchi',
       'Mangalore Kitchen', 'MoXa Bistro', 'Mouthful', 'Namdhari's Salad Bar',
       'Namma Kudla', 'Nandi Upachar', 'New Tandoor', 'Palmgrove',
       'Prakriti Delux', 'S G Rao’s Military Hotel', 'Sabari Juice Junction',
       'Sea Spice by 7 Star', 'Seafood Dot Grill', 'Sendhoor Coffee',
       'Sri Raghavendra Stores', 'Tasty Bites',
       'The Coastal Crew by Fujian on 24th',
       'The Lobby Lounge - The Ritz-Carlton', 'Udupi Grand',
       'Urban Solace - Café for the Soul'],
      dtype='object', name='rest_name')